Repository nvisionative/nvQuickLoanCalculator, pull requests merged in 2024-07, with the labels that each got.

#7 Implemented field validation and calculations
  src/components/nvq-loan-calculator/nvq-loan-calculator.tsx
  src/components/nvq-loan-calculator/readme.md
Labels: enhancement

#10 Added build orchestration
  .github/workflows/Deploy.yml
  .github/workflows/PR_Validation.yml
  .gitignore
  .nuke/build.schema.json
  .nuke/parameters.json
  build.cmd
  build.ps1
  build.sh
  build/.editorconfig
  build/Build.cs
  build/Configuration.cs
  build/Directory.Build.props
  build/Directory.Build.targets
  build/_build.csproj
  build/_build.csproj.DotSettings
  nvQuickLoanCalculator.sln
  package-lock.json
  package.json
Labels: build

#11 Merged multiple build fixes from first attempt at a release branch
  .github/workflows/Deploy.yml
  .github/workflows/PR_Validation.yml
  .nuke/build.schema.json
  build/Build.cs
  package-lock.json
  package.json
Labels: build

#12 Adds mergeable and dependabot configs
  .github/dependabot.yaml
  .github/mergeable.yaml
Labels: build

#17 Added scope to package name
  package.json
Labels: build

#19 Fixed a typo in yaml file names
  .github/dependabot.yml
  .github/mergeable.yml
Labels: maintenance

#21 Updated `develop` with latest fixes on `release/1.0.0`
  src/components/nvq-loan-calculator/nvq-loan-calculator.scss
  src/components/nvq-loan-calculator/nvq-loan-calculator.tsx
  src/index.html
Labels: bug

#22 Updated to allow empty total amount and down payment with default value
  package-lock.json
  src/components/nvq-loan-calculator/nvq-loan-calculator.tsx
Labels: enhancement

#23 Merged `release/1.0.1` into `main` for `1.0.1` release
  .github/dependabot.yml
  .github/mergeable.yml
  package-lock.json
  src/components/nvq-loan-calculator/nvq-loan-calculator.tsx
Labels: maintenance

#24 Added slot for monthly payment footer
  src/components/nvq-loan-calculator/nvq-loan-calculator.tsx
  src/components/nvq-loan-calculator/readme.md
Labels: enhancement

#25 Release/1.1.0
  src/components/nvq-loan-calculator/nvq-loan-calculator.tsx
  src/components/nvq-loan-calculator/readme.md
Labels: build

#26 Removed disclaimer margin to accommodate new monthly-payment-footer slot
  src/components/nvq-loan-calculator/nvq-loan-calculator.scss
Labels: enhancement

#27 Release/1.1.1
  src/components/nvq-loan-calculator/nvq-loan-calculator.scss
Labels: build
